{
 "title": "tailchat-server",
 "time": { "from": "2022-06-07T10:46:00.836Z", "to": "2022-06-07T11:46:00.836Z" },
 "panels": [
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "os_memory_used{namespace=\"tailchat\"}"
    }
   ]
  },
  {
   "title": "CPU 利用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "os_cpu_utilization" }
   ]
  },
  {
   "title": "请求分布",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "moleculer_request_total", "legendFormat": "{{action}}({{caller}})" }
   ]
  },
  {
   "title": "当前正在处理中的请求",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 12, "y": 9 },
   "targets": [
    { "expr": "moleculer_request_active", "legendFormat": "{{action}}" }
   ]
  },
  {
   "title": "接收包流量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "moleculer_transporter_packets_received_bytes"
    }
   ]
  },
  {
   "title": "发送包流量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "moleculer_transporter_packets_sent_bytes"
    }
   ]
  }
 ]
}